from typing import Dict, Any

METRIC_CATALOG: Dict[str, Dict[str, Any]] = {
    "total_sales": {
        "description": "Sum of sales revenue",
        "formula": "SUM(sales.sales_amount)",
        "required_columns": ["sales.sales_amount"],
        "valid_aggregations": ["SUM", "AVG"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name", "state_group", "sale_date", "promotion_id"],
        "comparison_required": False
    },
    "total_units": {
        "description": "Sum of physical units sold",
        "formula": "SUM(sales.units_sold)",
        "required_columns": ["sales.units_sold"],
        "valid_aggregations": ["SUM", "AVG"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name", "sale_date", "promotion_id"],
        "comparison_required": False
    },
    "average_selling_price": {
        "description": "Weighted average net selling price of products",
        "formula": "SUM(sales.sales_amount) / SUM(sales.units_sold)",
        "required_columns": ["sales.sales_amount", "sales.units_sold"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name", "sale_date"],
        "comparison_required": False
    },
    "average_daily_sales": {
        "description": "Average daily units sold",
        "formula": "AVG(daily_sales_units)",
        "required_columns": ["sales.units_sold", "sales.sale_date"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name"],
        "comparison_required": False
    },
    "sales_growth_percentage": {
        "description": "Percentage growth/decline of sales between two periods",
        "formula": "((Sales(Period 2) - Sales(Period 1)) / Sales(Period 1)) * 100",
        "required_columns": ["sales.sales_amount", "sales.sale_date"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name"],
        "comparison_required": True
    },
    "month_over_month_growth": {
        "description": "Growth rate compared to previous month",
        "formula": "((Sales(Month N) - Sales(Month N-1)) / Sales(Month N-1)) * 100",
        "required_columns": ["sales.sales_amount", "sales.sale_date"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name"],
        "comparison_required": True
    },
    "revenue_contribution_percentage": {
        "description": "Share of total company revenue generated by a dimension value",
        "formula": "(SUM(Sales for Dim Value) / SUM(Total Sales)) * 100",
        "required_columns": ["sales.sales_amount"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_name", "category", "brand", "region_name"],
        "comparison_required": False
    },
    "promotion_sales": {
        "description": "Sales revenue generated during promotion periods",
        "formula": "SUM(sales.sales_amount) WHERE sales.promotion_id IS NOT NULL",
        "required_columns": ["sales.sales_amount", "sales.promotion_id"],
        "valid_aggregations": ["SUM"],
        "compatible_dimensions": ["product_id", "product_name", "category", "brand", "region_name", "promotion_id"],
        "comparison_required": False
    },
    "baseline_sales": {
        "description": "Sales units/revenue estimate without promotion effects",
        "formula": "Average sales of comparable non-promotional period",
        "required_columns": ["sales.sales_amount", "sales.units_sold", "sales.sale_date", "sales.promotion_id"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name", "promotion_id"],
        "comparison_required": True
    },
    "promotion_uplift_percentage": {
        "description": "Percentage increase in sales associated with a promotion vs baseline",
        "formula": "((Promotion Sales - Baseline Sales) / Baseline Sales) * 100",
        "required_columns": ["sales.sales_amount", "sales.promotion_id"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name", "promotion_id"],
        "comparison_required": True
    },
    "opening_inventory": {
        "description": "Beginning stock levels for a period",
        "formula": "inventory.opening_inventory on first date of period",
        "required_columns": ["inventory.opening_inventory", "inventory.snapshot_date"],
        "valid_aggregations": ["SUM", "AVG"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name", "snapshot_date"],
        "comparison_required": False
    },
    "closing_inventory": {
        "description": "Ending stock levels for a period",
        "formula": "inventory.closing_inventory on last date of period",
        "required_columns": ["inventory.closing_inventory", "inventory.snapshot_date"],
        "valid_aggregations": ["SUM", "AVG"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name", "snapshot_date"],
        "comparison_required": False
    },
    "inventory_reduction_percentage": {
        "description": "Reduction in inventory levels during a campaign",
        "formula": "((Opening Inventory - Closing Inventory) / Opening Inventory) * 100",
        "required_columns": ["inventory.opening_inventory", "inventory.closing_inventory"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name"],
        "comparison_required": False
    },
    "sell_through_percentage": {
        "description": "Percentage of inventory sold during the period",
        "formula": "(SUM(sales.units_sold) / (Opening Inventory + Received Inventory)) * 100",
        "required_columns": ["sales.units_sold", "inventory.opening_inventory", "inventory.received_units"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name"],
        "comparison_required": False
    },
    "stockout_risk": {
        "description": "Percentage of days where closing inventory is zero",
        "formula": "(Days with Closing Inventory = 0 / Total Days in Period) * 100",
        "required_columns": ["inventory.closing_inventory", "inventory.snapshot_date"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name"],
        "comparison_required": False
    },
    "excess_inventory": {
        "description": "Stock levels exceeding 30 days of average sales volume",
        "formula": "closing_inventory - (average_daily_sales * 30)",
        "required_columns": ["inventory.closing_inventory", "sales.units_sold"],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": ["product_id", "product_name", "category", "region_name"],
        "comparison_required": False
    },
    "data_completeness_percentage": {
        "description": "Percentage of non-null records in a table",
        "formula": "(Non-null rows / Total rows) * 100",
        "required_columns": [],
        "valid_aggregations": ["CALCULATED"],
        "compatible_dimensions": [],
        "comparison_required": False
    }
}
